version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: core-banking-mysql
    environment:
      MYSQL_DATABASE: core_banking_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/complete_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - banking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  core-banking-app:
    build: .
    container_name: core-banking-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:mysql://mysql:3306/core_banking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: banking_user
      DB_PASSWORD: banking_pass
      JWT_SECRET: mySecretKey123456789012345678901234567890
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - banking-network
    volumes:
      - app_logs:/var/log/core-banking
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - banking-network

volumes:
  mysql_data:
  app_logs:

networks:
  banking-network:
    driver: bridge