
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_banking_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
logging:
  level:
    com.corebanking: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
